services:
    web:
        image: img-web
        ports:
            - 80:80
        volumes:
            - "/home/jenkins/workspace/Pipeline-BGApp/web:/var/www/html:ro"
        networks:
            - appnet
        depends_on:
            - db
    db:
        image: img-db
        networks:
            - appnet
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    appnet:
