services:
    web:
        image: img-web
        ports:
            - 80:80
        volumes:
            - "$(pwd)Pipeline-BGApp//web:/var/www/html:ro"
        networks:
            - appnet
    db:
        image: img-db
        networks:
            - appnet
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    appnet:
