services:
    web:
        image: ilkothetiger/bgapp-web
        ports:
            - 80:80
        volumes:
            - "/home/jenkins/workspace/Pipeline-BGApp/web:/var/www/html:ro"
        networks:
            - app-network
        depends_on:
            - db
    db:
        image: ilkothetiger/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network:
